# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$line_break\
$container\
$character"""

[git_branch]
ignore_branches = ["main", "master"]
